Import foreman_probing_core
adamruzicka/smart-proxy-probing pull request #2
Opened 2021-05-07 10:45 UTC by adamruzicka

2021-10-20 11:33 UTC, ekohl requested changes

2021-10-20 11:33 UTC, ekohl commented on lib/foreman_probing_core.rb
> +  if ForemanTasksCore.dynflow_present?
Should this be updated now? AFAIK Dynflow should always be present and we want to get rid of `ForemanTasksCore`, right?

2021-10-20 11:33 UTC, ekohl commented on lib/smart-proxy-probing.rb
> +        @nmap_available = true
Should this use `Proxy::Util::which('nmap')` instead?

2021-10-20 11:33 UTC, ekohl commented on smart-proxy-probing.gemspec
> +  s.add_dependency('ruby-nmap', '~> 0.9')
```suggestion
  gem.add_dependency('foreman-tasks-core', '~> 0.1')
  gem.add_dependency('ruby-nmap', '~> 0.9')
```

2021-10-20 11:33 UTC, ekohl commented on lib/smart-proxy-probing/actions.rb
> +    require 'foreman_probing_core/actions/use_probe'
This require doesn't look correct anymore.

2021-10-20 11:33 UTC, ekohl commented on lib/smart-proxy-probing/probes.rb
> +    require 'foreman_probing_core/probes/icmp'
These don't look correct.

2021-10-20 12:35 UTC, ekohl approved these changes

2021-10-21 10:48 UTC, merged

2021-10-21 10:48 UTC, adamruzicka commented
Thank you @ekohl !